package store

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/giammarcoferranti/deja/internal/store/gen"
	_ "github.com/mattn/go-sqlite3"
)

// The queries below are generated by sqlc from internal/store/sqlc/query.sql —
// run `make sqlc` after editing it. sqlc is a build-time tool only: the code it
// emits imports nothing beyond context, database/sql and time, so it adds no
// runtime dependency and ~16KB to the binary.
//
// The generated types are not deja's types, and deliberately are not used
// beyond this file. sqlc models the schema exactly, which means
// command_stats.command comes back as sql.NullString (AutoMigrate declared it
// without NOT NULL) and every integer as int64. Tightening the column would
// mean rebuilding the table on every existing install, which is precisely what
// the migration in this file exists to avoid — so the mapping happens here, at
// the boundary, and the rest of deja keeps seeing plain string/int.

type Command struct {
	ID         uint
	Command    string
	Directory  string
	Timestamp  time.Time
	ExitCode   int
	DurationMS int
	SessionID  string
}

type CommandStat struct {
	Command  string
	Count    int
	LastUsed time.Time
}

type Sequence struct {
	PrevCommand string
	NextCommand string
	Count       int
}

// schemaVersion is the user_version this build expects. Bump it and add a step
// to migrations when the schema changes.
const schemaVersion = 1

// migrations[i] takes the database from user_version i to i+1.
//
// Step 0 is written to match, statement for statement, the schema GORM's
// AutoMigrate produced — same column order, same types, same index names. That
// is deliberate: databases created by earlier releases already have every one
// of these objects, so `IF NOT EXISTS` makes the whole step a no-op and the
// migration simply stamps user_version. Existing installs are adopted in place,
// never rewritten.
//
// SQLite ignores the length in a declared type, so GORM's `size:2048` on the
// command columns produced plain `text`. Reproduced as-is rather than
// "corrected", because a differing declared type would make an adopted database
// disagree with a freshly created one.
var migrations = [][]string{
	{
		"CREATE TABLE IF NOT EXISTS `commands` (`id` integer PRIMARY KEY AUTOINCREMENT,`command` text NOT NULL,`directory` text NOT NULL,`timestamp` datetime NOT NULL,`exit_code` integer NOT NULL,`duration_ms` integer NOT NULL,`session_id` text NOT NULL)",
		"CREATE INDEX IF NOT EXISTS `idx_commands_command` ON `commands`(`command`)",
		"CREATE INDEX IF NOT EXISTS `idx_commands_directory` ON `commands`(`directory`)",
		"CREATE INDEX IF NOT EXISTS `idx_commands_timestamp` ON `commands`(`timestamp`)",
		"CREATE INDEX IF NOT EXISTS `idx_commands_session` ON `commands`(`session_id`)",
		"CREATE TABLE IF NOT EXISTS `command_stats` (`command` text,`count` integer NOT NULL DEFAULT 0,`last_used` datetime NOT NULL,PRIMARY KEY (`command`))",
		"CREATE INDEX IF NOT EXISTS `idx_command_stats_last_used` ON `command_stats`(`last_used`)",
		"CREATE TABLE IF NOT EXISTS `sequences` (`prev_command` text NOT NULL,`next_command` text NOT NULL,`count` integer NOT NULL DEFAULT 0)",
		"CREATE UNIQUE INDEX IF NOT EXISTS `idx_seq_pair` ON `sequences`(`prev_command`,`next_command`)",
	},
}

// open returns a connection pool configured the way every deja process wants
// it. One connection, always: SQLite permits a single writer regardless, and
// serialising through one handle turns what would be SQLITE_BUSY contention
// between this process's own goroutines into ordinary queueing. Every query
// here is short, so the queue never grows.
func open(path string) (*sql.DB, error) {
	db, err := sql.Open("sqlite3", path)
	if err != nil {
		return nil, fmt.Errorf("open sqlite %q: %w", path, err)
	}
	db.SetMaxOpenConns(1)

	if _, err := db.Exec("PRAGMA busy_timeout=5000;"); err != nil {
		db.Close()
		return nil, fmt.Errorf("set busy_timeout: %w", err)
	}
	return db, nil
}

// InitDB opens the database for reading and writing, and brings the schema up
// to date.
func InitDB(path string) (*sql.DB, error) {
	db, err := open(path)
	if err != nil {
		return nil, err
	}

	if err := db.Ping(); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping sqlite: %w", err)
	}

	// Lock the database down before any statement touches it. It holds shell
	// history in plaintext, so it gets the same treatment zsh gives
	// ~/.zsh_history.
	//
	// Placement matters: SQLite creates the -wal and -shm sidecars lazily, on
	// the first real work against the database, and gives them the main file's
	// mode as it stands at that moment. Tightening first means they are born
	// 0600. Under GORM that first work was AutoMigrate; here it is the WAL
	// pragma below, so this has to stay above it.
	if err := restrictDBFiles(path); err != nil {
		db.Close()
		return nil, err
	}

	if _, err := db.Exec("PRAGMA journal_mode=WAL;"); err != nil {
		db.Close()
		return nil, fmt.Errorf("enable WAL: %w", err)
	}

	if err := migrate(db); err != nil {
		db.Close()
		return nil, err
	}

	return db, nil
}

// OpenReader opens the database for reading without running migrations.
//
// Migrating is the right thing when a writer is about to touch the database and
// the wrong thing on the suggestion path, which opens the database once per
// keystroke whenever the daemon is unreachable.
//
// Deliberately not `mode=ro`: a read-only open of a WAL database fails outright
// when the -shm file is absent, which is exactly the daemon-is-down situation
// this path exists to serve. Skipping the migration is the win; refusing to
// open is not a trade worth making for it.
func OpenReader(path string) (*sql.DB, error) {
	db, err := open(path)
	if err != nil {
		return nil, err
	}
	// Same lock-down as InitDB. This path is read-only in intent, but opening a
	// database that does not exist creates it, and SQLite would leave it 0644.
	if err := restrictDBFiles(path); err != nil {
		db.Close()
		return nil, err
	}
	return db, nil
}

// restrictDBFiles makes the database owner-only.
//
// The main file always exists by the time this runs. The sidecars usually do
// not (see InitDB on when they appear), so they are chmod'd best-effort — that
// branch is what repairs a database left behind by an earlier version, where a
// -wal from an unclean shutdown can hold the most recent commands at 0644.
func restrictDBFiles(path string) error {
	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("chmod %s: %w", path, err)
	}
	for _, suffix := range []string{"-wal", "-shm"} {
		if err := os.Chmod(path+suffix, 0o600); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("chmod %s: %w", path+suffix, err)
		}
	}
	return nil
}

// migrate applies any migration steps this database has not seen, tracked by
// SQLite's user_version. Forward only.
func migrate(db *sql.DB) error {
	var version int
	if err := db.QueryRow("PRAGMA user_version;").Scan(&version); err != nil {
		return fmt.Errorf("read user_version: %w", err)
	}
	if version >= schemaVersion {
		return nil
	}

	for v := version; v < schemaVersion; v++ {
		tx, err := db.Begin()
		if err != nil {
			return fmt.Errorf("begin migration %d: %w", v, err)
		}
		for _, stmt := range migrations[v] {
			if _, err := tx.Exec(stmt); err != nil {
				tx.Rollback()
				return fmt.Errorf("migration %d (%s): %w", v, firstWords(stmt), err)
			}
		}
		// PRAGMA user_version does not accept a bound parameter, so it is
		// formatted in. v+1 is an int from this loop, never user input.
		if _, err := tx.Exec(fmt.Sprintf("PRAGMA user_version=%d;", v+1)); err != nil {
			tx.Rollback()
			return fmt.Errorf("stamp user_version %d: %w", v+1, err)
		}
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("commit migration %d: %w", v, err)
		}
	}
	return nil
}

// firstWords trims a statement down to something readable in an error.
func firstWords(stmt string) string {
	if i := strings.Index(stmt, "("); i > 0 {
		stmt = stmt[:i]
	}
	return strings.TrimSpace(stmt)
}

// Keeps multi-row INSERTs under SQLite's SQLITE_MAX_VARIABLE_NUMBER
// (999 on older builds). Widest row is Command at 7 columns, so 100
// rows ≈ 700 host params.
const importBatchSize = 100

func SaveImportBatch(db *sql.DB, commands []Command) error {
	if len(commands) == 0 {
		return nil
	}
	seqRows := createSeq(commands)
	statsRows := createCommandStat(commands)

	ctx := context.Background()
	return inTx(db, func(tx *sql.Tx) error {
		q := gen.New(db).WithTx(tx)

		// One generated call per row rather than the multi-row INSERT GORM
		// built. Same round trips inside the transaction, and no
		// SQLITE_MAX_VARIABLE_NUMBER ceiling to chunk around — importBatchSize
		// stays only as documentation of the constraint that shaped the
		// batching.
		for i := range commands {
			c := &commands[i]
			// :execlastid rather than :exec, so the primary key can be written
			// back onto the caller's slice the way GORM did.
			id, err := q.InsertCommand(ctx, gen.InsertCommandParams{
				Command:    c.Command,
				Directory:  c.Directory,
				Timestamp:  c.Timestamp,
				ExitCode:   int64(c.ExitCode),
				DurationMs: int64(c.DurationMS),
				SessionID:  c.SessionID,
			})
			if err != nil {
				return err
			}
			c.ID = uint(id)
		}

		for _, st := range statsRows {
			if err := q.UpsertCommandStat(ctx, gen.UpsertCommandStatParams{
				Command:  sql.NullString{String: st.Command, Valid: true},
				Count:    int64(st.Count),
				LastUsed: st.LastUsed,
			}); err != nil {
				return err
			}
		}

		for _, sq := range seqRows {
			if err := q.UpsertSequence(ctx, gen.UpsertSequenceParams{
				PrevCommand: sq.PrevCommand,
				NextCommand: sq.NextCommand,
				Count:       int64(sq.Count),
			}); err != nil {
				return err
			}
		}

		return nil
	})
}

// inTx runs fn in a transaction, rolling back on error or panic.
func inTx(db *sql.DB, fn func(*sql.Tx) error) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer func() {
		if p := recover(); p != nil {
			tx.Rollback()
			panic(p)
		}
	}()
	if err := fn(tx); err != nil {
		tx.Rollback()
		return err
	}
	return tx.Commit()
}

type seqKey struct {
	prev string
	next string
}

func createSeq(commands []Command) []Sequence {
	if len(commands) < 2 {
		return nil
	}

	counts := make(map[seqKey]int)

	for i := 1; i < len(commands); i++ {
		if IgnoredCommand(commands[i-1].Command) || IgnoredCommand(commands[i].Command) {
			continue
		}
		prev := strings.TrimSpace(commands[i-1].Command)
		next := strings.TrimSpace(commands[i].Command)

		if prev == "" || next == "" {
			continue
		}

		k := seqKey{prev: prev, next: next}
		counts[k]++
	}

	out := make([]Sequence, 0, len(counts))
	for k, n := range counts {
		out = append(out, Sequence{
			PrevCommand: k.prev,
			NextCommand: k.next,
			Count:       n,
		})
	}
	return out

}

func createCommandStat(commands []Command) []CommandStat {
	if len(commands) == 0 {
		return nil
	}
	counts := map[string]int{}
	lastUsed := map[string]time.Time{}

	for _, c := range commands {
		if IgnoredCommand(c.Command) {
			continue
		}
		cmd := strings.TrimSpace(c.Command)
		counts[cmd]++
		if t, ok := lastUsed[cmd]; !ok || c.Timestamp.After(t) {
			lastUsed[cmd] = c.Timestamp
		}
	}

	out := make([]CommandStat, 0, len(counts))
	for cmd, n := range counts {
		out = append(out, CommandStat{
			Command:  cmd,
			Count:    n,
			LastUsed: lastUsed[cmd],
		})
	}
	return out
}

// IgnoredCommand reports whether cmd must never be persisted: it is blank, or
// it begins with whitespace. A leading space is zsh's HIST_IGNORE_SPACE privacy
// gesture (see internal/shell/zsh.sh), and this is the last chokepoint before
// SQLite. Go cannot see the shell's setopt state, so the rule is applied
// unconditionally — nothing useful is lost, since suggestions are always
// offered in trimmed form anyway.
//
// zsh's own rule is "the first character is a space or a tab", so this
// deliberately does not consider other unicode whitespace.
func IgnoredCommand(cmd string) bool {
	return strings.TrimSpace(cmd) == "" || strings.TrimLeft(cmd, " \t") != cmd
}

// RecordCommand inserts a single command row and upserts the derived
// command_stats + sequences rows in one transaction. prevCommand may be empty
// (the very first command in a session has no predecessor) — in that case
// the sequences upsert is skipped.
func RecordCommand(db *sql.DB, cmd Command, prevCommand string) error {
	if IgnoredCommand(cmd.Command) {
		return nil
	}
	key := strings.TrimSpace(cmd.Command)

	// An ignored predecessor must not survive as sequences.prev_command: that
	// would store it verbatim even though the command itself was never
	// recorded. zsh clears __deja_prev for us, but a shell without the hook
	// (or a hand-rolled `deja record`) can still pass one in.
	if IgnoredCommand(prevCommand) {
		prevCommand = ""
	}

	ctx := context.Background()
	return inTx(db, func(tx *sql.Tx) error {
		q := gen.New(db).WithTx(tx)

		if _, err := q.InsertCommand(ctx, gen.InsertCommandParams{
			Command:    cmd.Command,
			Directory:  cmd.Directory,
			Timestamp:  cmd.Timestamp,
			ExitCode:   int64(cmd.ExitCode),
			DurationMs: int64(cmd.DurationMS),
			SessionID:  cmd.SessionID,
		}); err != nil {
			return err
		}

		if err := q.UpsertCommandStat(ctx, gen.UpsertCommandStatParams{
			Command:  sql.NullString{String: key, Valid: true},
			Count:    1,
			LastUsed: cmd.Timestamp,
		}); err != nil {
			return err
		}

		prev := strings.TrimSpace(prevCommand)
		if prev == "" {
			return nil
		}
		return q.UpsertSequence(ctx, gen.UpsertSequenceParams{
			PrevCommand: prev,
			NextCommand: key,
			Count:       1,
		})
	})
}

func GetCommandStats(db *sql.DB) ([]CommandStat, error) {
	rows, err := gen.New(db).ListCommandStats(context.Background())
	if err != nil {
		return nil, err
	}

	out := make([]CommandStat, 0, len(rows))
	for _, r := range rows {
		out = append(out, CommandStat{
			Command:  r.Command.String,
			Count:    int(r.Count),
			LastUsed: r.LastUsed,
		})
	}
	return out, nil
}

// get the commands where prev match
func GetSequenceCounts(db *sql.DB, prev string) (map[string]int, error) {
	rows, err := gen.New(db).SequenceCountsFor(context.Background(), prev)
	if err != nil {
		return nil, err
	}

	commands := make(map[string]int, len(rows))
	for _, r := range rows {
		commands[r.NextCommand] = int(r.Count)
	}
	return commands, nil
}

// get the commands where directory match
func GetDirCountsForCommand(db *sql.DB, cmd string) (map[string]int, error) {
	rows, err := gen.New(db).DirCountsForCommand(context.Background(), cmd)
	if err != nil {
		return nil, err
	}

	counts := make(map[string]int, len(rows))
	for _, r := range rows {
		counts[r.Directory] = int(r.N)
	}
	return counts, nil
}
